/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bookshop;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
/**
 *
 * @author acer
 */
public class Change extends javax.swing.JFrame {

    /**
     * Creates new form Change
     */
    public Change() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfNusername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNpassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        tfOpassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHANGE LOGIN");
        jLabel1.setAlignmentX(540.0F);
        jLabel1.setAlignmentY(100.0F);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 208, 50));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText(" BACK");
        btnBack.setAlignmentX(540.0F);
        btnBack.setAlignmentY(100.0F);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 115, -1));

        btnConfirm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConfirm.setText("CONFIRM");
        btnConfirm.setAlignmentX(540.0F);
        btnConfirm.setAlignmentY(100.0F);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, 124, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" New Username");
        jLabel2.setAlignmentX(540.0F);
        jLabel2.setAlignmentY(100.0F);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 144, 42));

        tfNusername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfNusername.setAlignmentX(540.0F);
        tfNusername.setAlignmentY(100.0F);
        tfNusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNusernameActionPerformed(evt);
            }
        });
        getContentPane().add(tfNusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 181, 42));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" New Password");
        jLabel3.setAlignmentX(540.0F);
        jLabel3.setAlignmentY(100.0F);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, -1, 43));

        tfNpassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfNpassword.setAlignmentX(540.0F);
        tfNpassword.setAlignmentY(100.0F);
        tfNpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tfNpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, 181, 42));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Old Password");
        jLabel4.setAlignmentX(540.0F);
        jLabel4.setAlignmentY(100.0F);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, 149, 43));

        tfOpassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfOpassword.setAlignmentX(540.0F);
        tfOpassword.setAlignmentY(100.0F);
        tfOpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tfOpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 181, 42));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ho.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-550, -230, 2660, 1360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         // Close Register form
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
       String oldPassword = new String(tfOpassword.getPassword());
    String newUsername = tfNusername.getText();
    String newPassword = new String(tfNpassword.getPassword());

    if (oldPassword.isEmpty() || newUsername.isEmpty() || newPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields are required!", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try (Connection conn = DBConnection.getConnection()) {
        // Check if old password matches the existing one
        String checkSql = "SELECT * FROM login WHERE Password = ?";
        PreparedStatement checkPst = conn.prepareStatement(checkSql);
        checkPst.setString(1, oldPassword);
        ResultSet rs = checkPst.executeQuery();

        if (rs.next()) {
            // If old password is correct, update username & password
            String updateSql = "UPDATE login SET Username = ?, Password = ? WHERE Password = ?";
            PreparedStatement updatePst = conn.prepareStatement(updateSql);
            updatePst.setString(1, newUsername);
            updatePst.setString(2, newPassword);
            updatePst.setString(3, oldPassword);

            int rowsUpdated = updatePst.executeUpdate();
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Username and password updated successfully!");
                this.dispose(); // Close Change form
                new login().setVisible(true); // Open login form
            } else {
                JOptionPane.showMessageDialog(this, "Update failed!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Old password is incorrect!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void tfNusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNusernameActionPerformed
        // TODO add your handling code here:
        tfNpassword.requestFocus();
    }//GEN-LAST:event_tfNusernameActionPerformed

    private void tfNpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNpasswordActionPerformed
        // TODO add your handling code here:
        tfOpassword.requestFocus();
     
    }//GEN-LAST:event_tfNpasswordActionPerformed

    private void tfOpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOpasswordActionPerformed
        // TODO add your handling code here:
        btnConfirm.requestFocus();
    }//GEN-LAST:event_tfOpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Change().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField tfNpassword;
    private javax.swing.JTextField tfNusername;
    private javax.swing.JPasswordField tfOpassword;
    // End of variables declaration//GEN-END:variables
}
