/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bookshop;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class Sale extends javax.swing.JFrame {

    /**
     * Creates new form Sales
     */
    public Sale() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tfBcode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfQuantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfBcode1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfQuantity1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfCname = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnConfirm1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Book Code");

        tfBcode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Quantity");

        tfQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantityActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DELETE FIELD");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to BookShop Management System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 538, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Book Code");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, -1, -1));

        tfBcode1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfBcode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBcode1ActionPerformed(evt);
            }
        });
        getContentPane().add(tfBcode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 97, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 78, -1));

        tfQuantity1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfQuantity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantity1ActionPerformed(evt);
            }
        });
        getContentPane().add(tfQuantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 97, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Customer Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, 125, -1));

        tfCname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfCname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCnameActionPerformed(evt);
            }
        });
        getContentPane().add(tfCname, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 400, 97, -1));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, -1, -1));

        btnConfirm1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConfirm1.setText("CONFIRM");
        btnConfirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirm1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 530, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SALE FIELD");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 321, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ho.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-550, -230, 2660, 1360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantityActionPerformed

    private void tfQuantity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantity1ActionPerformed

    private void tfCnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCnameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        new Home().setVisible(true);   
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnConfirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirm1ActionPerformed
       // TODO add your handling code here:
 String bookCode = tfBcode1.getText().trim();   // Book Code
    String customerName = tfCname.getText().trim(); // Customer Name
    String quantityText = tfQuantity1.getText().trim(); // Quantity to be sold

    // Validation: Check if fields are empty
    if (bookCode.isEmpty() || customerName.isEmpty() || quantityText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields are required!", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validate quantity as a positive integer
    int quantity = 0;
    try {
        quantity = Integer.parseInt(quantityText);
        if (quantity <= 0) {
            JOptionPane.showMessageDialog(this, "Quantity must be greater than zero.", "Invalid Quantity", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid integer for quantity.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Establish a database connection
    try (Connection conn = DBConnection.getConnection()) {
        // Step 1: Check if the book exists and has enough stock
        String checkStockQuery = "SELECT quantity, price FROM books WHERE book_code = ?";
        PreparedStatement checkStockStmt = conn.prepareStatement(checkStockQuery);
        checkStockStmt.setString(1, bookCode);
        ResultSet rs = checkStockStmt.executeQuery();

        if (rs.next()) {
            int availableQuantity = rs.getInt("quantity");
            double pricePerBook = rs.getDouble("price");

            if (availableQuantity < quantity) {
                JOptionPane.showMessageDialog(this, "Not enough stock available.", "Insufficient Stock", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Calculate total price for confirmation
            double totalPrice = quantity * pricePerBook;

            // Confirmation dialog for sale
            int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to sell " + quantity + " copies of \"" + bookCode + "\" for a total of " + totalPrice + "?",
                "Confirm Sale",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

            if (confirm != JOptionPane.YES_OPTION) {
                return; // User chose not to proceed with the sale
            }

            // Step 2: Insert sale record into sales table
            String insertSaleQuery = "INSERT INTO sales (book_code, quantity_sold, total_price, customer_name) VALUES (?, ?, ?, ?)";
            PreparedStatement insertSaleStmt = conn.prepareStatement(insertSaleQuery);
            insertSaleStmt.setString(1, bookCode);
            insertSaleStmt.setInt(2, quantity);
            insertSaleStmt.setDouble(3, totalPrice);
            insertSaleStmt.setString(4, customerName);  // Corrected

            int saleInserted = insertSaleStmt.executeUpdate();
            if (saleInserted > 0) {
                // Step 3: Update book quantity in books table
                String updateBookQuery = "UPDATE books SET quantity = quantity - ? WHERE book_code = ?";
                PreparedStatement updateBookStmt = conn.prepareStatement(updateBookQuery);
                updateBookStmt.setInt(1, quantity);
                updateBookStmt.setString(2, bookCode);

                int bookUpdated = updateBookStmt.executeUpdate();

                if (bookUpdated > 0) {
                    JOptionPane.showMessageDialog(this, "Sale successful!\nCustomer: " + customerName, "Success", JOptionPane.INFORMATION_MESSAGE);
                    
                    // Clear input fields after successful sale
                    tfBcode1.setText("");
                    tfQuantity1.setText("");
                    tfCname.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Error updating book stock.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Failed to record sale.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Book not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnConfirm1ActionPerformed

    private void tfBcode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBcode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBcode1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfBcode;
    private javax.swing.JTextField tfBcode1;
    private javax.swing.JTextField tfCname;
    private javax.swing.JTextField tfQuantity;
    private javax.swing.JTextField tfQuantity1;
    // End of variables declaration//GEN-END:variables

    private void Home() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
